name: Auto Clone on Push

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger on

jobs:
  clone:
    name: Clone Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Repository
        run: |
          # Replace <repository_url> with the URL of the GitHub repository you want to clone
          cd /var/www/html && rm -rf *.* && git clone https://github.com/gohilkrishna/Pre_Onboarding_Test.git
